name: Docker Image CI
  
on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/metaphor:${GITHUB_REF##*/}

      - name: Push image to dockerhub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/metaphor:${GITHUB_REF##*/}
